# Generated by Django 3.2.18 on 2023-04-15 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Visitor',
        ),
    ]
