# Generated by Django 3.2.18 on 2023-04-15 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20230415_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='Pid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.prisoner'),
        ),
    ]
