# Generated by Django 3.2.18 on 2023-04-15 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_visitor_pid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='Pid',
        ),
    ]
