# Generated by Django 3.2.18 on 2023-04-15 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_visitor_pid'),
    ]

    operations = [
        migrations.CreateModel(
            name='sho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoId', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
            ],
        ),
    ]
