# Generated by Django 3.2.18 on 2023-04-15 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_guard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sho',
            old_name='shoId',
            new_name='ShoId',
        ),
    ]
