# Generated by Django 3.2.18 on 2023-04-15 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_shoid_sho_shoid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sho',
            name='ShoId',
        ),
    ]
