# Generated by Django 3.2.18 on 2023-04-15 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_sho_shoid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sho',
        ),
    ]
